### ISSUE TITLE
clean up known_hosts

### ISSUE THREAD

**Issue by xarem** [whatwedo/Vaprobash#1]
Either on boot, on creation or on destruction of a vagrant machine, the `~/.known_hosts` should be modified with the key of the machine.
## on boot

on every boot, remove old [hostnames](https://github.com/whatwedo/Vaprobash/blob/develop/Vagrantfile#L15) and their fingerprints and add the current machine fingerprint
## on creation

add the generated machine fingerprint to known_hosts and remove existing fingerprints with the same hostname
## on destruction

remove the fingerprint of the hostname

in my opinion, the most suitable method would be to clean up existing fingerprints and add the new fingerprint on creation of a machine and remove the fingerprint on destruction. it could be a security problem if we do this at the time of booting up the machine.

what's your opinion, @n3r0-ch?

**Comment by n3r0-ch** [comment]
I think this would be very useful. Probably the required actions could be executed by the [vagrant-triggers](https://github.com/emyl/vagrant-triggers)Plugin. I don't rate your security concerns as to risky.
