### ISSUE TITLE
Make Apache and PHP use higher upload and post max size per default

### ISSUE THREAD

**Issue by renestalder** [whatwedo/Vaprobash#3]
At least 15M to match most cases with CMS sites, where images may be up to 10 Mb.

**Comment by xarem** [comment]
agree

_PHP 7_

```
echo "upload_max_filesize = 32M" >> /etc/php/7.0/fpm/php.ini
echo "post_max_size = 32M" >> /etc/php/7.0/fpm/php.ini
```

_PHP 5_

```
echo "upload_max_filesize = 32M" >> /etc/php5/fpm/php.ini
echo "post_max_size = 32M" >> /etc/php5/fpm/php.ini
```

_Apache_
by default `LimitRequestBody` is set to `0`, which means Apache doesn't have an input limit for the request body.

I'll make a pull request for this
